import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../data/database.dart';
import '../domain/schedule.dart';
import '../domain/streaks.dart';
// HabitScheduleHistoryData is generated by Drift — comes from database.dart

// ── Database ──────────────────────────────────────────────────────────────────

final dbProvider = Provider<AppDatabase>(
  (ref) => throw UnimplementedError('dbProvider must be overridden in main.dart'),
);

// ── Auth ──────────────────────────────────────────────────────────────────────

// 0 = not logged in. Set after login/register; guards all user-scoped providers.
final currentUserIdProvider = StateProvider<int>((ref) => 0);

// ── Streams ───────────────────────────────────────────────────────────────────

final groupsProvider = StreamProvider<List<Group>>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return const Stream.empty();
  return ref.watch(dbProvider).watchGroups(userId);
});

final habitsProvider = StreamProvider<List<Habit>>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return const Stream.empty();
  return ref.watch(dbProvider).watchActiveHabits(userId);
});

final archivedHabitsProvider = StreamProvider<List<Habit>>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return const Stream.empty();
  return ref.watch(dbProvider).watchArchivedHabits(userId);
});

final recentCompletionsProvider =
    StreamProvider<Map<int, List<Completion>>>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return const Stream.empty();
  final sinceUtc = localMidnightUtc(
    DateTime.now().subtract(const Duration(days: 90)),
  );
  return ref.watch(dbProvider).watchRecentCompletions(sinceUtc).map((list) {
    final map = <int, List<Completion>>{};
    for (final c in list) (map[c.habitId] ??= []).add(c);
    return map;
  });
});

final vacationsProvider = StreamProvider<List<Vacation>>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return const Stream.empty();
  return ref.watch(dbProvider).watchVacations(userId);
});

final scheduleHistoryProvider =
    StreamProvider<Map<int, List<HabitScheduleHistoryData>>>(
  (ref) => ref.watch(dbProvider).watchAllScheduleHistory(),
);

final yearlyCompletionsProvider =
    StreamProvider<Map<int, List<Completion>>>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return const Stream.empty();
  final sinceUtc = localMidnightUtc(
    DateTime.now().subtract(const Duration(days: 365)),
  );
  return ref.watch(dbProvider).watchRecentCompletions(sinceUtc).map((list) {
    final map = <int, List<Completion>>{};
    for (final c in list) (map[c.habitId] ??= []).add(c);
    return map;
  });
});

// ── View state ────────────────────────────────────────────────────────────────

final currentViewProvider = StateProvider<String>((ref) => 'daily');
final focusedHabitIdProvider = StateProvider<int?>((ref) => null);
final selectedDayProvider = StateProvider<DateTime>((ref) => DateTime.now());

// ── Domain models ─────────────────────────────────────────────────────────────

class DailyHabit {
  final Habit habit;
  final Completion? todayCompletion;
  final StreakResult streaks;

  const DailyHabit({
    required this.habit,
    required this.todayCompletion,
    required this.streaks,
  });

  bool get isDoneToday {
    if (todayCompletion == null) return false;
    final t = habit.tracking;
    if (t == 'counter' || t == 'duration') {
      final target = habit.target ?? 1;
      return todayCompletion!.value >= target;
    }
    return todayCompletion!.value > 0;
  }

  double get todayValue => todayCompletion?.value ?? 0.0;
}

class DailyGroup {
  final Group group;
  final List<DailyHabit> habits;

  const DailyGroup({required this.group, required this.habits});

  int get doneCount => habits.where((h) => h.isDoneToday).length;
}

class DailyState {
  final List<DailyGroup> groups;
  final DateTime today;
  final StreakResult overallStreak;
  final int availableShields; // always 0 until Phase 8
  final int totalCompletionsAllTime;

  const DailyState({
    required this.groups,
    required this.today,
    required this.overallStreak,
    required this.availableShields,
    required this.totalCompletionsAllTime,
  });

  int get totalDone => groups.fold(0, (sum, g) => sum + g.doneCount);
  int get totalHabits => groups.fold(0, (sum, g) => sum + g.habits.length);
}

// ── Computed daily state ──────────────────────────────────────────────────────

final dailyStateProvider = Provider<AsyncValue<DailyState>>((ref) {
  final groupsAV = ref.watch(groupsProvider);
  final habitsAV = ref.watch(habitsProvider);
  final recentAV = ref.watch(recentCompletionsProvider);
  final vacAV = ref.watch(vacationsProvider);
  final historyAV = ref.watch(scheduleHistoryProvider);
  final selectedDay = ref.watch(selectedDayProvider);

  for (final av in [groupsAV, habitsAV, recentAV, vacAV, historyAV]) {
    if (av.isLoading) return const AsyncValue.loading();
    if (av.hasError) return AsyncValue.error(av.error!, av.stackTrace!);
  }

  final groups = groupsAV.requireValue;
  final habits = habitsAV.requireValue;
  final recentMap = recentAV.requireValue;
  final vacList = vacAV.requireValue;
  final historyMap = historyAV.requireValue;
  final today = DateTime.now();
  final selectedDayUtc = localMidnightUtc(selectedDay);

  // Compute streaks for ALL active habits.
  final allStreaks = <int, StreakResult>{
    for (final h in habits)
      h.id: computeStreaks(
        h, recentMap[h.id] ?? const [], today, vacList,
        historyMap[h.id] ?? const [],
      ),
  };
  final vacDays = buildVacationDaySet(vacList);
  var totalCompletions = 0;
  for (final h in habits) {
    for (final c in recentMap[h.id] ?? const <Completion>[]) {
      if (!vacDays.contains(c.day.toUtc())) totalCompletions++;
    }
  }
  final overallStreak =
      computeOverallStreak(habits, recentMap, vacList, historyMap, today);

  final dailyGroups = groups
      .map((group) {
        final groupHabits = habits
            .where((h) => h.groupId == group.id)
            // start date filter
            .where((h) =>
                !selectedDayUtc.isBefore(localMidnightUtc(h.startDate)))
            // end date filter
            .where((h) => h.endDate == null ||
                !selectedDayUtc.isAfter(localMidnightUtc(h.endDate!)))
            // schedule filter using effective history for the selected day
            .where((h) {
              final entry = effectiveScheduleAt(
                  historyMap[h.id] ?? const [], selectedDayUtc);
              return isDueOnSchedule(
                  entry?.schedule ?? h.schedule, selectedDay);
            })
            .map((h) {
              final comps = recentMap[h.id] ?? const <Completion>[];
              Completion? selectedComp;
              for (final c in comps) {
                if (c.day.toUtc() == selectedDayUtc) {
                  selectedComp = c;
                  break;
                }
              }
              return DailyHabit(
                habit: h,
                todayCompletion: selectedComp,
                streaks: allStreaks[h.id]!,
              );
            })
            .toList();
        return DailyGroup(group: group, habits: groupHabits);
      })
      .where((g) => g.habits.isNotEmpty)
      .toList();

  return AsyncValue.data(DailyState(
    groups: dailyGroups,
    today: selectedDay,
    overallStreak: overallStreak,
    availableShields: overallStreak.displayStreak ~/ 7,
    totalCompletionsAllTime: totalCompletions,
  ));
});

// ── Settings ──────────────────────────────────────────────────────────────────

// Global (not per-user) settings backed by the AppSettings Drift table.

final themeIdProvider = StreamProvider<String>((ref) => ref
    .watch(dbProvider)
    .watchSetting('themeId')
    .map((v) => v ?? 'matrix'));

final fontSizeProvider = StreamProvider<String>((ref) => ref
    .watch(dbProvider)
    .watchSetting('fontSize')
    .map((v) => v ?? 'md'));

final allowFutureMarkingProvider = StreamProvider<bool>((ref) => ref
    .watch(dbProvider)
    .watchSetting('allowFutureMarking')
    .map((v) => v == 'true'));

final confirmDestructiveProvider = StreamProvider<bool>((ref) => ref
    .watch(dbProvider)
    .watchSetting('confirmDestructive')
    .map((v) => v != 'false')); // default true

// ── Current user ─────────────────────────────────────────────────────────────

final currentUserProvider = FutureProvider<User?>((ref) {
  final userId = ref.watch(currentUserIdProvider);
  if (userId == 0) return Future.value(null);
  return ref.watch(dbProvider).getUserById(userId);
});

// ── User name (display name of logged-in user) ────────────────────────────────

final userNameProvider = Provider<String>((ref) {
  return ref.watch(currentUserProvider).valueOrNull?.displayName ?? 'you';
});

// ── Per-day completion ratios for the week strip ──────────────────────────────

class DayRatio {
  final DateTime day;
  final int done;
  final int due;
  const DayRatio({required this.day, required this.done, required this.due});

  double get ratio => due == 0 ? 0 : (done / due).clamp(0, 1).toDouble();
}

// Returns the completion ratio for each of the 7 days in the week containing
// [selectedDay]. Uses recentMap + active habits + schedule history.
List<DayRatio> weeklyRatios(
  DateTime selectedDay,
  List<Habit> habits,
  Map<int, List<Completion>> recentMap,
  Map<int, List<HabitScheduleHistoryData>> historyMap,
  List<Vacation> vacations,
) {
  final vacDays = buildVacationDaySet(vacations);
  final monday = DateTime(
    selectedDay.year,
    selectedDay.month,
    selectedDay.day - (selectedDay.weekday - 1),
  );
  final out = <DayRatio>[];
  for (var i = 0; i < 7; i++) {
    final day = DateTime(monday.year, monday.month, monday.day + i);
    final dayUtc = localMidnightUtc(day);
    if (vacDays.contains(dayUtc)) {
      out.add(DayRatio(day: day, done: 0, due: 0));
      continue;
    }
    var due = 0;
    var done = 0;
    for (final h in habits) {
      final startUtc = localMidnightUtc(h.startDate.toLocal());
      if (dayUtc.isBefore(startUtc)) continue;
      if (h.endDate != null &&
          dayUtc.isAfter(localMidnightUtc(h.endDate!.toLocal()))) continue;
      final entry = effectiveScheduleAt(historyMap[h.id] ?? const [], dayUtc);
      if (!isDueOnSchedule(entry?.schedule ?? h.schedule, day)) continue;
      due++;
      final comps = recentMap[h.id] ?? const [];
      if (comps.any((c) => c.day.toUtc() == dayUtc)) done++;
    }
    out.add(DayRatio(day: day, done: done, due: due));
  }
  return out;
}

final weeklyRatiosProvider = Provider<List<DayRatio>>((ref) {
  final habitsAV = ref.watch(habitsProvider);
  final recentAV = ref.watch(recentCompletionsProvider);
  final historyAV = ref.watch(scheduleHistoryProvider);
  final vacAV = ref.watch(vacationsProvider);
  final selectedDay = ref.watch(selectedDayProvider);
  if (habitsAV.isLoading || recentAV.isLoading || historyAV.isLoading) {
    return const [];
  }
  if (habitsAV.hasError || recentAV.hasError || historyAV.hasError) {
    return const [];
  }
  return weeklyRatios(selectedDay, habitsAV.requireValue,
      recentAV.requireValue, historyAV.requireValue,
      vacAV.valueOrNull ?? const []);
});

